import turtle
#turtle.shape('turtle')
#finn=turtle.clone()
#finn.shape('square')
#finn.goto(100,0)
#finn.goto(100,100)
#finn.goto(0,100)
#finn.goto(0,0)
#charlie=turtle.clone()
#charlie.shape('triangle')
#charlie.goto(100,0)
#charlie.goto(50,100)
#charlie.goto(0,0)
#finn.goto(300,300)
#a=finn.stamp()
#finn.goto(100,100)
#finn.stamp()
#finn.goto(0,0)
#finn.clearstamps(2)
#t=turtle.Turtle()
#p=turtle.Turtle()
#turtle.bgcolor('purple')
#t.shape('arrow')
#t.color('green')
#t.pensize(5)
#t.right(90)
#t.fd(150)
#t.left(90)
#t.fd(75)
#t.color('blue')
#t.left(90)
#t.fd(150)
#p.shape('circle')
#p.pensize(2)
#p.color('yellow')
#p.left(90)
#p.fd(150)
#p.left(90)
#p.fd(75)
#p.left(90)
#p.color('white')
#p.fd(150)
t=turtle.Turtle()
def up():
    t.setheading(90)
    t.fd(50)
def down():
    t.setheading(270)
    t.fd(50)
def left():
    t.setheading(180)
    t.fd(50)
def right():
    t.setheading(0)
    t.fd(50)    
turtle.onkeypress(up,"w")
turtle.onkeypress(down,"s")
turtle.onkeypress(left,"a")
turtle.onkeypress(right,"d")
turtle.listen()

turtle.mainloop()
